In [1]:
# For default Johnson-Cook material model
E = 110000  # 1.1e8
nu = 0.31  # 0.3


def getLameParameters(E, nu):
    lam = E * nu / ((1 + nu) * (1 - 2 * nu))
    mu = E / (2 * (1 + nu))
    return lam, mu


print(getLameParameters(E, nu))

(68501.40618722378, 41984.732824427476)


In [2]:
import numpy as np

array = np.linspace(0, 1, 10)
array[3] = -np.nan
# print(f"{np.any(np.isnan(array))=}")
if np.any(np.isnan(array)):
    indice = np.where(np.isnan(array))
    print("array contains nan, idx = ", indice)

array contains nan, idx =  (array([3]),)


In [3]:
class Data:
    def __init__(self, i):
        self.i = i

    def __str__(self) -> str:
        return f"Data {self.i}"


d = Data(1)


def test_data():
    d = Data(2)
    print(d)


print(d)
test_data()

Data 1
Data 2


In [4]:
import numpy as np

array = np.array([1, 2, 3])
Array = np.array(
    [
        array,
    ]
    * 3
)

Array[0][0] = 100

print(Array)

[[100   2   3]
 [  1   2   3]
 [  1   2   3]]


In [5]:
long_array = np.linspace(0, 1, 10)

long_array_reshaped = np.reshape(long_array, (-1, 2))
print(len(long_array_reshaped))
print(long_array_reshaped.shape[1])
print(np.sum(long_array_reshaped, axis=1))
print(np.max(long_array_reshaped, axis=1))
for e in long_array_reshaped:
    print(e)

5
2
[0.11111111 0.55555556 1.         1.44444444 1.88888889]
[0.11111111 0.33333333 0.55555556 0.77777778 1.        ]
[0.         0.11111111]
[0.22222222 0.33333333]
[0.44444444 0.55555556]
[0.66666667 0.77777778]
[0.88888889 1.        ]


In [6]:
A = np.array([[1, 2], [2, 3]])
# eigs = np.linalg.eigvals(A)
# print(eigs)
# # print(np.linalg.eig(A))
eigvals, eigvecs = np.linalg.eig(A)
print(f"{eigvals=}")
print(f"{eigvecs=}")
print(f"{eigvecs.T=}")
for i in range(len(eigvals)):
    print(f"{i}: eigval = {eigvals[i]}, eigvec = {eigvecs[:, i]}")

eigvals=array([-0.23606798,  4.23606798])
eigvecs=array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]])
eigvecs.T=array([[-0.85065081,  0.52573111],
       [-0.52573111, -0.85065081]])
0: eigval = -0.2360679774997898, eigvec = [-0.85065081  0.52573111]
1: eigval = 4.23606797749979, eigvec = [-0.52573111 -0.85065081]


In [7]:
# M = np.array((3,2))
M = np.zeros((3, 2, 2))
V = np.zeros(12)
# M = np.append(M, np.array([[1, 2], [3, 4]]))
M[0] = np.array([[1, 2], [3, 4]])
M[1] = np.array([[5, 6], [7, 8]])
M[2] = np.array([[9, 10], [11, 12]])
print(M)
print(M.flatten())
V[:] = M.flatten()
print(V)

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [8]:
a1 = np.linspace(0, 1, 10)
a2 = np.linspace(1, 2, 10)
print(a1)
print(a2)
for i in range(len(a1)):
    print(a1[i] * a2[i])
print(a1 * a2)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
0.0
0.12345679012345678
0.2716049382716049
0.4444444444444444
0.6419753086419753
0.8641975308641976
1.111111111111111
1.3827160493827158
1.6790123456790123
2.0
[0.         0.12345679 0.27160494 0.44444444 0.64197531 0.86419753
 1.11111111 1.38271605 1.67901235 2.        ]


In [ ]:
import gmsh

w = 10
h = 4
mesh_x = 400
crack_length = 4
thickness = 1

gmsh.initialize()
# Define the geometry
h_e = w / mesh_x
# crack_length_factor = crack_length / length
width = h_e * 0.5
max_element_size = h_e
min_element_size = h_e
gmsh.model.occ.addPoint(-w / 2, -h / 2, 0, max_element_size, 1)
gmsh.model.occ.addPoint(w / 2, -h / 2, 0, max_element_size, 2)
gmsh.model.occ.addPoint(w / 2, h / 2, 0, max_element_size, 3)
gmsh.model.occ.addPoint(-w / 2, h / 2, 0, max_element_size, 4)

gmsh.model.occ.addPoint(-crack_length / 2, width / 2, 0, min_element_size, 5)
gmsh.model.occ.addPoint(crack_length / 2, width / 2, 0, min_element_size, 6)
gmsh.model.occ.addPoint(crack_length / 2, -width / 2, 0, min_element_size, 7)
gmsh.model.occ.addPoint(-crack_length / 2, -width / 2, 0, min_element_size, 8)

gmsh.model.occ.addLine(1, 2, 1)
gmsh.model.occ.addLine(2, 3, 2)
gmsh.model.occ.addLine(3, 4, 3)
gmsh.model.occ.addLine(4, 1, 4)

gmsh.model.occ.addLine(5, 6, 5)
# gmsh.model.occ.addLine(6, 7, 6)
gmsh.model.occ.addCircle(
    crack_length / 2,
    0,
    0,
    r=width / 2,
    tag=6,
    angle1=-np.pi / 2,
    angle2=np.pi / 2,
)
gmsh.model.occ.addLine(7, 8, 7)
# gmsh.model.occ.addLine(8, 5, 8)
gmsh.model.occ.addCircle(
    -crack_length / 2,
    0,
    0,
    r=width / 2,
    tag=8,
    angle1=np.pi / 2,
    angle2=-np.pi / 2,
)

gmsh.model.occ.addCurveLoop([1, 2, 3, 4], 1)
gmsh.model.occ.addCurveLoop([5, 6, 7, 8], 2)

gmsh.model.occ.addPlaneSurface([1, 2], 1)
gmsh.model.occ.synchronize()

gmsh.model.addPhysicalGroup(2, [1], 1, "Plane")

# Configure the meshing algorithm
gmsh.option.setNumber("Mesh.RecombinationAlgorithm", 2)
gmsh.option.setNumber("Mesh.RecombineAll", 1)
gmsh.option.setNumber("Mesh.Algorithm", 8)

gmsh.model.mesh.generate(2)
gmsh.model.mesh.removeDuplicateNodes()

gmsh.model.mesh.optimize("Netgen")

gmsh.model.occ.extrude([(2, 1)], 0, 0, thickness, [1], recombine=True)
gmsh.model.occ.synchronize()

gmsh.model.addPhysicalGroup(3, [1], 1, "Model")

gmsh.model.mesh.generate(3)

# gmsh.write("mesh.inp")
# gmsh.write("mesh.msh")

# gmsh.fltk.run()

gmsh.finalize()


Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 10%] Meshing curve 2 (Line)
Info    : [ 20%] Meshing curve 3 (Line)
Info    : [ 30%] Meshing curve 4 (Line)
Info    : [ 40%] Meshing curve 5 (Line)
Info    : [ 50%] Meshing curve 6 (Circle)
Info    : [ 60%] Meshing curve 7 (Line)
Info    : [ 70%] Meshing curve 8 (Circle)
Info    : [ 80%] Meshing curve 9 (Circle)
Info    : [ 90%] Meshing curve 10 (Line)
Info    : [100%] Meshing curve 11 (Circle)
Info    : Done meshing 1D (Wall 0.000699195s, CPU 0.002471s)
Info    : Meshing 2D...
Info    : Meshing surface 1 (Plane, Frontal-Delaunay for Quads)
Info    : Simple recombination completed (Wall 0.345964s, CPU 0.343816s): 19310 quads, 754 triangles, 0 invalid quads, 0 quads with Q < 0.1, avg Q = 0.943962, min Q = 0.203026
Info    : Simple recombination completed (Wall 0.53621s, CPU 0.532315s): 79502 quads, 0 triangles, 0 invalid quads, 0 quads with Q < 0.1, avg Q = 0.947192, min Q = 0.459988
Info    : Done meshing 2D (W

In [17]:
a = np.less(2, [1, 2, 3])
print(a)
print(np.all(a))

[False False  True]
False


In [ ]:
np.linalg.norm([[1, 2, 3], [4, 5, 6]], axis=1)

array([3.74165739, 8.77496439])

In [ ]:
import numpy as np

a = np.array([0.2, 0.1])

(
    (np.array([[1, 2, 3], [4, 5, 6]]) > 2).astype(float)
    * np.array([[1, 2, 3], [4, 5, 6]])
    * a[:, None]
) ** 2


array([[0.  , 0.  , 0.36],
       [0.16, 0.25, 0.36]])

In [22]:
A = np.array([[1, -1], [1, 1]])
print(np.einsum("ij,jk,lk->il", A, np.eye(2), A))
print(np.matmul(A, np.eye(2)))
print(np.matmul(A, A.T))

[[2. 0.]
 [0. 2.]]
[[ 1. -1.]
 [ 1.  1.]]
[[2 0]
 [0 2]]


In [3]:
import dataclasses


@dataclasses.dataclass
class Material:
    rho: float
    lame: float
    mu: float


@dataclasses.dataclass
class JohnsonCook(Material):
    initial_yield_stress: float
    strength_coefficient: float
    strain_rate_strength_coefficient: float
    hardening_exponent: float
    temperature_exponent: float
    reference_strain_rate: float
    reference_temperature: float
    melting_temperature: float


jc1 = JohnsonCook(
    rho=7800,
    lame=110000,
    mu=1,
    initial_yield_stress=500,
    strength_coefficient=600,
    strain_rate_strength_coefficient=0.01,
    hardening_exponent=0.1,
    temperature_exponent=0.02,
    reference_strain_rate=1.0,
    reference_temperature=300,
    melting_temperature=1500,
)
print(jc1.mu)

1


In [ ]:
import numpy as np

A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"{np.linalg.norm(A, axis=0)=}")
print(f"{np.linalg.norm(A, axis=1)=}")
print(f"{np.linalg.norm(A)=}")

np.linalg.norm(A, axis=0)=array([5.09901951, 6.32455532, 7.61577311, 8.94427191])
np.linalg.norm(A, axis=1)=array([ 5.47722558, 13.19090596])
np.linalg.norm(A)=np.float64(14.2828568570857)


In [1]:
import numpy as np
A = np.linspace(0, 9e-3, 4)
np.sum(A)


np.float64(0.018)