In [1]:
# For default Johnson-Cook material model
E = 1.1e5  # 1.1e8
nu = 0.31  # 0.3


def getLameParameters(E, nu):
    lam = E * nu / ((1 + nu) * (1 - 2 * nu))
    mu = E / (2 * (1 + nu))
    return lam, mu


print(getLameParameters(E, nu))

(68501.40618722378, 41984.732824427476)


In [2]:
import numpy as np

array = np.linspace(0, 1, 10)
array[3] = -np.nan
# print(f"{np.any(np.isnan(array))=}")
if np.any(np.isnan(array)):
    indice = np.where(np.isnan(array))
    print("array contains nan, idx = ", indice)

array contains nan, idx =  (array([3]),)


In [3]:
class Data:
    def __init__(self, i):
        self.i = i

    def __str__(self) -> str:
        return f"Data {self.i}"


d = Data(1)


def test_data():
    d = Data(2)
    print(d)


print(d)
test_data()

Data 1
Data 2


In [4]:
import numpy as np

array = np.array([1, 2, 3])
Array = np.array(
    [
        array,
    ]
    * 3
)

Array[0][0] = 100

print(Array)

[[100   2   3]
 [  1   2   3]
 [  1   2   3]]


In [5]:
long_array = np.linspace(0, 1, 10)

long_array_reshaped = np.reshape(long_array, (-1, 2))
print(len(long_array_reshaped))
print(long_array_reshaped.shape[1])
print(np.sum(long_array_reshaped, axis=1))
print(np.max(long_array_reshaped, axis=1))
for e in long_array_reshaped:
    print(e)

5
2
[0.11111111 0.55555556 1.         1.44444444 1.88888889]
[0.11111111 0.33333333 0.55555556 0.77777778 1.        ]
[0.         0.11111111]
[0.22222222 0.33333333]
[0.44444444 0.55555556]
[0.66666667 0.77777778]
[0.88888889 1.        ]


In [6]:
A = np.array([[1, 2], [2, 3]])
# eigs = np.linalg.eigvals(A)
# print(eigs)
# # print(np.linalg.eig(A))
eigvals, eigvecs = np.linalg.eig(A)
print(f"{eigvals=}")
print(f"{eigvecs=}")
print(f"{eigvecs.T=}")
for i in range(len(eigvals)):
    print(f"{i}: eigval = {eigvals[i]}, eigvec = {eigvecs[:, i]}")

eigvals=array([-0.23606798,  4.23606798])
eigvecs=array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]])
eigvecs.T=array([[-0.85065081,  0.52573111],
       [-0.52573111, -0.85065081]])
0: eigval = -0.2360679774997898, eigvec = [-0.85065081  0.52573111]
1: eigval = 4.23606797749979, eigvec = [-0.52573111 -0.85065081]


In [7]:
# M = np.array((3,2))
M = np.zeros((3, 2, 2))
V = np.zeros(12)
# M = np.append(M, np.array([[1, 2], [3, 4]]))
M[0] = np.array([[1, 2], [3, 4]])
M[1] = np.array([[5, 6], [7, 8]])
M[2] = np.array([[9, 10], [11, 12]])
print(M)
print(M.flatten())
V[:] = M.flatten()
print(V)

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [8]:
a1 = np.linspace(0, 1, 10)
a2 = np.linspace(1, 2, 10)
print(a1)
print(a2)
for i in range(len(a1)):
    print(a1[i] * a2[i])
print(a1 * a2)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
0.0
0.12345679012345678
0.2716049382716049
0.4444444444444444
0.6419753086419753
0.8641975308641976
1.111111111111111
1.3827160493827158
1.6790123456790123
2.0
[0.         0.12345679 0.27160494 0.44444444 0.64197531 0.86419753
 1.11111111 1.38271605 1.67901235 2.        ]


In [ ]:
import gmsh

principle_direction = 10
h = 4
mesh_x = 400
crack_length = 4
thickness = 1

gmsh.initialize()
# Define the geometry
h_e = principle_direction / mesh_x
# crack_length_factor = crack_length / length
width = h_e * 0.5
max_element_size = h_e
min_element_size = h_e
gmsh.model.occ.addPoint(-principle_direction / 2, -h / 2, 0, max_element_size, 1)
gmsh.model.occ.addPoint(principle_direction / 2, -h / 2, 0, max_element_size, 2)
gmsh.model.occ.addPoint(principle_direction / 2, h / 2, 0, max_element_size, 3)
gmsh.model.occ.addPoint(-principle_direction / 2, h / 2, 0, max_element_size, 4)

gmsh.model.occ.addPoint(-crack_length / 2, width / 2, 0, min_element_size, 5)
gmsh.model.occ.addPoint(crack_length / 2, width / 2, 0, min_element_size, 6)
gmsh.model.occ.addPoint(crack_length / 2, -width / 2, 0, min_element_size, 7)
gmsh.model.occ.addPoint(-crack_length / 2, -width / 2, 0, min_element_size, 8)

gmsh.model.occ.addLine(1, 2, 1)
gmsh.model.occ.addLine(2, 3, 2)
gmsh.model.occ.addLine(3, 4, 3)
gmsh.model.occ.addLine(4, 1, 4)

gmsh.model.occ.addLine(5, 6, 5)
# gmsh.model.occ.addLine(6, 7, 6)
gmsh.model.occ.addCircle(
    crack_length / 2,
    0,
    0,
    r=width / 2,
    tag=6,
    angle1=-np.pi / 2,
    angle2=np.pi / 2,
)
gmsh.model.occ.addLine(7, 8, 7)
# gmsh.model.occ.addLine(8, 5, 8)
gmsh.model.occ.addCircle(
    -crack_length / 2,
    0,
    0,
    r=width / 2,
    tag=8,
    angle1=np.pi / 2,
    angle2=-np.pi / 2,
)

gmsh.model.occ.addCurveLoop([1, 2, 3, 4], 1)
gmsh.model.occ.addCurveLoop([5, 6, 7, 8], 2)

gmsh.model.occ.addPlaneSurface([1, 2], 1)
gmsh.model.occ.synchronize()

gmsh.model.addPhysicalGroup(2, [1], 1, "Plane")

# Configure the meshing algorithm
gmsh.option.setNumber("Mesh.RecombinationAlgorithm", 2)
gmsh.option.setNumber("Mesh.RecombineAll", 1)
gmsh.option.setNumber("Mesh.Algorithm", 8)

gmsh.model.mesh.generate(2)
gmsh.model.mesh.removeDuplicateNodes()

gmsh.model.mesh.optimize("Netgen")

gmsh.model.occ.extrude([(2, 1)], 0, 0, thickness, [1], recombine=True)
gmsh.model.occ.synchronize()

gmsh.model.addPhysicalGroup(3, [1], 1, "Model")

gmsh.model.mesh.generate(3)

# gmsh.write("mesh.inp")
# gmsh.write("mesh.msh")

# gmsh.fltk.run()

gmsh.finalize()


Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 10%] Meshing curve 2 (Line)
Info    : [ 20%] Meshing curve 3 (Line)
Info    : [ 30%] Meshing curve 4 (Line)
Info    : [ 40%] Meshing curve 5 (Line)
Info    : [ 50%] Meshing curve 6 (Circle)
Info    : [ 60%] Meshing curve 7 (Line)
Info    : [ 70%] Meshing curve 8 (Circle)
Info    : [ 80%] Meshing curve 9 (Circle)
Info    : [ 90%] Meshing curve 10 (Line)
Info    : [100%] Meshing curve 11 (Circle)
Info    : Done meshing 1D (Wall 0.000699195s, CPU 0.002471s)
Info    : Meshing 2D...
Info    : Meshing surface 1 (Plane, Frontal-Delaunay for Quads)
Info    : Simple recombination completed (Wall 0.345964s, CPU 0.343816s): 19310 quads, 754 triangles, 0 invalid quads, 0 quads with Q < 0.1, avg Q = 0.943962, min Q = 0.203026
Info    : Simple recombination completed (Wall 0.53621s, CPU 0.532315s): 79502 quads, 0 triangles, 0 invalid quads, 0 quads with Q < 0.1, avg Q = 0.947192, min Q = 0.459988
Info    : Done meshing 2D (W

In [17]:
a = np.less(2, [1, 2, 3])
print(a)
print(np.all(a))

[False False  True]
False


In [ ]:
np.linalg.norm([[1, 2, 3], [4, 5, 6]], axis=1)

array([3.74165739, 8.77496439])

In [ ]:
import numpy as np

a = np.array([0.2, 0.1])

(
    (np.array([[1, 2, 3], [4, 5, 6]]) > 2).astype(float)
    * np.array([[1, 2, 3], [4, 5, 6]])
    * a[:, None]
) ** 2


array([[0.  , 0.  , 0.36],
       [0.16, 0.25, 0.36]])

In [22]:
A = np.array([[1, -1], [1, 1]])
print(np.einsum("ij,jk,lk->il", A, np.eye(2), A))
print(np.matmul(A, np.eye(2)))
print(np.matmul(A, A.T))

[[2. 0.]
 [0. 2.]]
[[ 1. -1.]
 [ 1.  1.]]
[[2 0]
 [0 2]]


In [3]:
import dataclasses


@dataclasses.dataclass
class Material:
    rho: float
    lame: float
    mu: float


@dataclasses.dataclass
class JohnsonCook(Material):
    initial_yield_stress: float
    strength_coefficient: float
    strain_rate_strength_coefficient: float
    hardening_exponent: float
    temperature_exponent: float
    reference_strain_rate: float
    reference_temperature: float
    melting_temperature: float


jc1 = JohnsonCook(
    rho=7800,
    lame=110000,
    mu=1,
    initial_yield_stress=500,
    strength_coefficient=600,
    strain_rate_strength_coefficient=0.01,
    hardening_exponent=0.1,
    temperature_exponent=0.02,
    reference_strain_rate=1.0,
    reference_temperature=300,
    melting_temperature=1500,
)
print(jc1.mu)

1


In [ ]:
import numpy as np

A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"{np.linalg.norm(A, axis=0)=}")
print(f"{np.linalg.norm(A, axis=1)=}")
print(f"{np.linalg.norm(A)=}")

np.linalg.norm(A, axis=0)=array([5.09901951, 6.32455532, 7.61577311, 8.94427191])
np.linalg.norm(A, axis=1)=array([ 5.47722558, 13.19090596])
np.linalg.norm(A)=np.float64(14.2828568570857)


In [1]:
import numpy as np
A = np.linspace(0, 9e-3, 4)
np.sum(A)


np.float64(0.018)

In [11]:
import numpy as np
increment_num = 20
load_steps = np.linspace(0, 1.1, increment_num + 1)[1:] ** 0.5
print(load_steps)

[0.23452079 0.33166248 0.40620192 0.46904158 0.52440442 0.57445626
 0.62048368 0.66332496 0.70356236 0.74161985 0.77781746 0.81240384
 0.84557673 0.87749644 0.90829511 0.93808315 0.96695398 0.99498744
 1.02225242 1.04880885]


In [48]:
import numpy as np

u_limit = 0.4
end_time = 4e-4

increment_num = 1000
delta_t = end_time / increment_num
load_steps = np.arange(delta_t, end_time + delta_t / 2, delta_t)

n = 20
n -= 1

print(f"{load_steps[n]=:.3e}")


def getLoad(t):
    def smooth(xi):
        return xi**3 * (10 - 15 * xi + 6 * xi * xi)

    return u_limit * smooth(t / end_time)


print(f"getLoad({load_steps[n]:.2e})={getLoad(load_steps[n]):.4e}")

# total = 0
# for i in range(n):
#     total += getLoad(load_steps[i])
# print(f"{total=:.3e}")

load_steps[n]=8.000e-06
getLoad(8.00e-06)=3.1048e-05


In [5]:
import numpy as np

u_limit = 0.4
end_time = 4e-4

increment_num = 50
delta_t = end_time / increment_num
load_steps = np.arange(delta_t, end_time + delta_t / 2, delta_t)[0 : int(increment_num / 2)]
print(load_steps)


[8.00e-06 1.60e-05 2.40e-05 3.20e-05 4.00e-05 4.80e-05 5.60e-05 6.40e-05
 7.20e-05 8.00e-05 8.80e-05 9.60e-05 1.04e-04 1.12e-04 1.20e-04 1.28e-04
 1.36e-04 1.44e-04 1.52e-04 1.60e-04 1.68e-04 1.76e-04 1.84e-04 1.92e-04
 2.00e-04]


In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.float64)

# Create the block matrix
M = np.zeros((A.shape[0], 2, 2))
M[:, 0, 0] = A[:, 0]
M[:, 1, 1] = A[:, 1]

principle_direction, principle_strain = np.linalg.eig(M)

print(principle_direction)
print()
print(principle_strain)



[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]

[[[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]]


In [5]:
import time

# print(time.struct_time([]))
print(time.localtime())

date_time = time.localtime()
# Print time like the log
print(time.strftime("[%Y-%m-%d %H:%M:%S]", date_time))

time.struct_time(tm_year=2024, tm_mon=12, tm_mday=8, tm_hour=13, tm_min=23, tm_sec=2, tm_wday=6, tm_yday=343, tm_isdst=0)
[2024-12-08 13:23:02]


In [ ]:
import numpy as np

lame = 68501.40618722378
mu = 41984.732824427476

d = 0.0157834
E = np.array(
    [[0.0240874, 0.021762, 0.0], [0.021762, 0.00809638, 0.0], [0.0, 0.0, 0.0171373]]
)

principle_strain, principle_direction = np.linalg.eig(E)

# sorted_idx = np.argsort(principle_strain)[-1::-1]
# principle_strain = principle_strain[sorted_idx]
# principle_direction =  principle_direction[sorted_idx, :]

print("principle_strain = ")
print(principle_strain)
print("\nprinciple_direction = ")
print(principle_direction)


tr = np.sum(principle_strain)
tr_factor = (tr > 0).astype(float)
factor = (principle_strain > 0).astype(float)
principle_stress = (
    2 * mu * principle_strain * (1 - factor * d) ** 2
    + lame * tr * (1 - tr_factor * d) ** 2
)
print("\nprinciple_stress = ")
print(principle_stress)

stress = np.einsum(
    "ij,jk,lk->il", principle_direction, np.diag(principle_stress), principle_direction
)
print("\nstress = ")
print(stress)

deviatoric_stress = stress - np.sum(np.diag(stress)) / 3 * np.eye(3)
print("\ndeviatoric_stress = ")
print(deviatoric_stress)

equivalent_stress = np.sqrt(1.5 * np.sum(deviatoric_stress**2))
print("\nequivalent_stress = ")
print(equivalent_stress)

principle_strain = 
[ 0.03927621 -0.00709243  0.0171373 ]

principle_direction = 
[[ 0.82002045 -0.57233422  0.        ]
 [ 0.57233422  0.82002045  0.        ]
 [ 0.          0.          1.        ]]

principle_stress = 
[6467.47135292 2677.20676161 4666.69802001]

stress = 
[[5225.90782205 1778.86882252    0.        ]
 [1778.86882252 3918.77029249    0.        ]
 [   0.            0.         4666.69802001]]

deviatoric_stress = 
[[ 622.1157772  1778.86882252    0.        ]
 [1778.86882252 -685.02175236    0.        ]
 [   0.            0.           62.90597517]]

equivalent_stress = 
3283.8213818580048


In [4]:
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

M = np.zeros((3, 2, 2))
print(M)
M[:,0,0] = data[0::4]

print(M)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[[1. 0.]
  [0. 0.]]

 [[5. 0.]
  [0. 0.]]

 [[9. 0.]
  [0. 0.]]]
